#!/bin/bash

DOMAIN=$2

#Colors
RED="\e[31m"
GREEN="\e[32m"
ENDCOLOR="\e[0m"

if [[ -z "$1" ]] || [[ -z "$2" ]];then
    echo -e "${RED}Usage ./subenum <WORDLIST> <DOMAIN>${ENDCOLOR}"
elif [[ "$3" == "--list" ]];then
    while read -r line; do
    SUB="$line"
    VART=$SUB".$DOMAIN"
    iptest=$(dig +short A $VART)
    if [[ -n "$iptest" ]];then
        echo "$VART"
    fi
    done < "$1"
else 
    while read -r line; do
    SUB="$line"
    VART=$SUB".$DOMAIN"
    iptest=$(dig +short A $VART)
    if [[ -z "$iptest" ]];then
        echo -e "${RED}"$VART" not found${ENDCOLOR}"
    else
        echo -e "${GREEN}"$VART" resolved to "$iptest"${ENDCOLOR}"
    fi
    done < "$1"
fi